name: Static website through cloudfront in AWS!!

on:
  push:
    branches:
         - main

jobs:
  aws-s3-cloudfront:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Deploy to AWS S3"
        run: aws s3 sync ./frontend s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete 

      - name: "Create AWS Cloudfront Invalidation"
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUD_DIST_ID }} --paths "/*"
